name: Andrew Cull
favicon: null
layout_spectrum: 0.8087453816551715
typography_spectrum: 0.067297249333933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020106'
    - '#fe6000'
    - '#fe9e00'
    - '#4a1801'
    - '#cd4400'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
