name: Andrew Cull
favicon: null
layout_spectrum: 0.75191
typography_spectrum: 0.13733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#717171'
    - '#474747'
    - '#dadada'
    - '#acacac'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
