name: Andrew Cull
favicon: null
layout_spectrum: 0.8087453816551715
typography_spectrum: 0.067297249333933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8386849539820105
  lightness: 0.29299597279168665
  saturation: 0.930639989906922
  rhythmicContrast: 0.5484520650934428
purpose: []
